baseurl = "https://kuda.pro"
languageCode = "ru-RU"
title = "Академия туризма - туристическое агентство в Анапе"
uglyurls = true

[params]
	description = "Туристическое агентство в Анапе. Отдых в лучших местах России и Мира. Продажа авиа и ж/д билетов"
	keywords = ["анапа", "турагентство"]
    bootstrapCols = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


[[menu.main]]
	name = "Главная"
	url = "/"
	weight = 20
[[menu.main]]
	name = "Страны"
	url = "/country.html"
	weight = 30
[[menu.main]]
	name = "Внутренний туризм"
	url = "/domestic_travel.html"
	weight = 40
[[menu.main]]
	name = "Отзывы"
	url = "/mention.html"
	weight = 50
[[menu.main]]
	name = "Блог"
	url = "/blog.html"
	weight = 60